services:
  devcontainer:
    image: ghcr.io/thechangelog/changelog-runtime:elixir-v1.18.3-erlang-v27.3.3-nodejs-v22.15.0
    volumes:
      - ../:/workspace
    network_mode: service:db

    # Installs "inotify-tools" to facilitate dynamic reloads of the website when changes are made and
    # "postgresql-client" to connect to the container running postgres (on localhost:5432) if postgres commands are needed.
    # Afterwards, sleeps forever so things don't shut down after the process ends.
    command: >
      bash -c "apt-get install --yes inotify-tools
      && apt-get install --yes postgresql-client
      && sleep infinity"

  db:
    # https://hub.docker.com/_/postgres
    image: postgres:16.8
    ports:
      - "4000:4000"
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgressql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: changelog_dev

  typesense:
    # https://hub.docker.com/r/typesense/typesense
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    command: "--data-dir /data --api-key=xyz --enable-cors"

volumes:
  postgres-data:
  typesense-data:
